ON-513: Direct Rental events
OriumNetwork/orium-rental-marketplace-contracts pull request #19
Opened 2023-11-03 18:34 UTC by karacurt

2023-11-04 03:31 UTC, ernanirst requested changes

2023-11-04 03:31 UTC, ernanirst commented on .gitignore
> +.openzeppelin/unknown-31337.json
Isn't this mumbai? Shouldn't we keep it?

2023-11-04 03:31 UTC, ernanirst commented on contracts/OriumMarketplace.sol
> +        uint256 duration,
Emit only duration, which is the value set by the user. The subgraph can compute expirationDate

2023-11-06 13:10 UTC, karacurt commented on .gitignore
> +.openzeppelin/unknown-31337.json
No, this is hardhat local chain

2023-11-06 19:16 UTC, ernanirst approved these changes

2023-11-06 19:26 UTC, merged