ON-547: OriumSftMarketplace core functions
OriumNetwork/orium-rental-marketplace-contracts pull request #23
Opened 2024-01-09 21:11 UTC by karacurt

2024-01-09 22:14 UTC, ernanirst requested changes

2024-01-09 22:14 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +     */
The comment does not match what the function does

2024-01-09 22:14 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +    }
Maybe let's combine these two functions and allow both the Contract Owner and the NFT Creator to call it. I see cases where users ask Orium to set the royalty, and others where users will want to set it themselves

2024-01-09 22:14 UTC, ernanirst commented on test/OriumSftMarketplace.test.ts
> +    describe('Core Functions', async () => {
Across the test files, break the lines between `describe` and `it` statements. It's very hard to read when everything is combined like this

2024-01-10 13:34 UTC, karacurt commented on test/OriumSftMarketplace.test.ts
> +    describe('Core Functions', async () => {
i tried, but prettier/lint still deleting the space between those two

2024-01-10 16:59 UTC, ernanirst approved these changes

2024-01-10 18:23 UTC, merged