ON-550: Cancel and end rental
OriumNetwork/orium-rental-marketplace-contracts pull request #26
Opened 2024-01-11 20:28 UTC by karacurt

2024-01-11 22:04 UTC, ernanirst requested changes

2024-01-11 22:04 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +    function createRentalOffer(RentalOffer memory _offer) external whenNotPaused {
Why did we change an external function parameter from calldata to memory?

2024-01-11 22:04 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +    );
Do we really need all these parameters here? What do we need on the subgraph? I believe only the `nonce` is required

2024-01-11 22:04 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +    event RentalOfferCancelled(uint256 indexed nonce, address indexed lender);
Do we need the lender here? It's always the `msg.sender`

2024-01-12 13:17 UTC, karacurt commented on contracts/OriumSftMarketplace.sol
> +    function createRentalOffer(RentalOffer memory _offer) external whenNotPaused {
because internal helper function `_createRentalOffer` was removed and it's logic was moved inside to createRentalOffer. In that logic, when a offer comes with commitmentId equals to zero. It's needed to commitTokens and set the commitmentId to the _offer struct. To do that, we reuse the _offer struct passed as parameter and only reassign commitmentId field. Unfortunately it's not possible to reassign values in calldata variables

2024-01-12 13:20 UTC, karacurt commented on contracts/OriumSftMarketplace.sol
> +    );
Since is the borrower who cancel it, it's still needed the lender param. Because each lender has its own's nonce (nonce is unique per lender, not for all lenders, so 2 lenders can have the same nonce, but still be separated, since the mapping is lender => nonce. We did this to avoid nonce conflicts between lenders

2024-01-12 13:30 UTC, karacurt commented on contracts/OriumSftMarketplace.sol
> +    }
- yes, if the sender is trying to cancel a nonce that it didn't set before, `nonceDeadline[msg.sender][nonce]` will return 0, and this will always be less than `block.timestamp` and it will revert with `Nonce expired or not used yet` message. Same thing happen to a nonce that expired or it was cancelled before, it will always have a past expiration and it will not be able to be cancelled anymore

- There only problem that can happen is to cancel a offer with an active rental, we don't need to update offers deadline in subgraph (since we have isCancelled flag), to allow borrowers to be able to call `endRental` with the original offer hash. Besides that case, i cannot see other scenario that the offer needs to be accessed after being canceled.

2024-01-14 22:38 UTC, ernanirst requested changes

2024-01-14 22:38 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +        );
Do we need all this information here? Correct me if I'm wrong, but I think all we need is the nonce, the borrower, and the expiration date

2024-01-14 22:38 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +        }
just improving docs
```suggestion
        // if there are no active rentals, release tokens (else, tokes will released vis `batchReleaseTokens`)
        if (rentals[_offerHash].expirationDate < block.timestamp) {
            IERC7589(rolesRegistryOf(_offer.tokenAddress)).releaseTokens(_offer.commitmentId);
        }
```

2024-01-14 22:38 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +            "OriumSftMarketplace: There is any active Rental"
```suggestion
            "OriumSftMarketplace: There are no active Rental"
```

2024-01-14 22:38 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +    function batchReleaseTokens(RentalOffer[] calldata _offer) external {
Missing function description

2024-01-14 22:38 UTC, ernanirst commented on contracts/libraries/LibOriumSftMarketplace.sol
> +    function transferFees(
Just checking. This is a external function that transfer tokens with no authentication. Can't an attacker trick the Marketplace to call this function and transfer tokens to itself?

2024-01-15 13:56 UTC, karacurt commented on contracts/libraries/LibOriumSftMarketplace.sol
> +    function transferFees(
No, because transferFees it's not a OriumSftMarketplace function (check the image bellow). Basically, this function will be deployed in a separated library, anyone can call the function there, but the library itself will not hold any tokens there.
![Uploading Screenshot 2024-01-15 at 10.54.31.png…]()

2024-01-15 15:22 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +            "OriumSftMarketplace: There are no active Rental"
```suggestion
            "OriumSftMarketplace: There are no active Rentals"
```

2024-01-15 15:22 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +    );
Make sense. But let's add the lender in the event `RentalOfferCancelled` too then. Just so we follow a patter of always including the lender and the nonce to identify offers on event

2024-01-15 15:29 UTC, ernanirst requested changes

2024-01-15 17:10 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +            "OriumSftMarketplace: There are no active Rental"
Now it has 2 s's

2024-01-15 17:13 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +        // if There are no active Rentalss, release tokens (else, tokens will be released via `batchReleaseTokens`)
```suggestion
        // if There are no active Rentals, release tokens (else, tokens will be released via `batchReleaseTokens`)
```

2024-01-15 17:33 UTC, merged