ON-551: add batchCommitTokensAndGrantRole function
OriumNetwork/orium-rental-marketplace-contracts pull request #27
Opened 2024-01-15 20:04 UTC by karacurt

2024-01-16 22:05 UTC, ernanirst requested changes

2024-01-16 22:05 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +    function batchCommitTokensAndGrantRole(CommitAndGrantRoleParams[] calldata _params) external {
We need to add the `commitmentId` to the `CommitAndGrantRoleParams` struct (similarly to Rental Offer). When `commitmentId` is not zero, this function will only `grantRole` ( this will be used to grant roles of NFTs that are already deposited)

2024-01-16 22:05 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +    function batchCommitTokensAndGrantRole(CommitAndGrantRoleParams[] calldata _params) external {
We also need an additional `batchRevokeRole` for users revoking roles that are not associated to a Rental Offer (required on direct rentals)

2024-01-16 22:05 UTC, ernanirst commented on test/OriumMarketplaceRoyalties.test.ts
> +import { ethers } from 'hardhat'
Bring `OriumMarketplaceRoyalties` test coverage to 100%

2024-01-17 12:36 UTC, karacurt commented on contracts/libraries/LibOriumSftMarketplace.sol
>          }
This is checked before calling the lib - https://github.com/OriumNetwork/orium-rental-marketplace-contracts/blob/495ea6426739e341669e3f08aea839ea0a68df95/contracts/OriumSftMarketplace.sol#L365

2024-01-17 16:23 UTC, ernanirst requested changes

2024-01-17 16:23 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +    function batchCommitTokensAndGrantRole(CommitAndGrantRoleParams[] memory _params) external {
It's a lot to copy all this data to memory, specially when the only data that can change is the `commitmentId`. Can we keep this in `calldata` and just call the correct `commitmentId` in the `grantRole` call?

2024-01-18 21:40 UTC, ernanirst approved these changes

2024-01-18 21:40 UTC, merged