ON-812: ERC721 Marketplace - Create Rental Offer
OriumNetwork/orium-rental-marketplace-contracts pull request #42
Opened 2024-04-16 19:16 UTC by karacurt

2024-04-17 23:56 UTC, ernanirst requested changes

2024-04-17 23:56 UTC, ernanirst commented on contracts/OriumNftMarketplace.sol
> +contract OriumNftMarketplace is Initializable, OwnableUpgradeable, PausableUpgradeable {
`OriumNftRentalMarketplace` or `NftRentalMarketplace`?
```suggestion
contract OriumNftRentalMarketplace is Initializable, OwnableUpgradeable, PausableUpgradeable {
```

2024-04-17 23:56 UTC, ernanirst commented on contracts/OriumNftMarketplace.sol
> +    function initialize(address _owner, address _oriumMarketplaceRoyalties) public initializer {
```suggestion
    function initialize(address _owner, address _oriumMarketplaceRoyalties) public external {
```

2024-04-17 23:56 UTC, ernanirst commented on contracts/OriumNftMarketplace.sol
> +    }
When the user creates a rental offer, the NFT stays on its, and when someone accepts it, it gets transferred to the contract. So when the offer expires, will we require users to withdraw their NFTs to create the offer again? Or will we allow users to create offers with NFTs that are in the contract but the offer is expired?

I'm leaning to the second one to mirror the behaviour we have for Wearables

2024-04-18 19:44 UTC, karacurt commented on contracts/OriumNftMarketplace.sol
> +contract OriumNftMarketplace is Initializable, OwnableUpgradeable, PausableUpgradeable {
The ERC1155 is called `OriumSftRentalMarketplace`, so i prefer this one to keep a 'standard'

2024-04-18 19:46 UTC, karacurt commented on contracts/OriumNftMarketplace.sol
> +contract OriumNftMarketplace is Initializable, OwnableUpgradeable, PausableUpgradeable {
I think RentalMarketplace is better than just Marketplace. But the ERC1155 is only `OriumSftMarketplace` also

2024-04-18 22:41 UTC, ernanirst requested changes

2024-04-18 22:41 UTC, ernanirst commented on contracts/OriumNftMarketplace.sol
> +    ) external {
```suggestion
    ) external whenNotPaused {
```

2024-04-18 22:41 UTC, ernanirst commented on contracts/OriumNftMarketplace.sol
> +contract OriumNftMarketplace is Initializable, OwnableUpgradeable, PausableUpgradeable {
Let's use `NftRentalMarketplace`, we can rename the other later if we want

2024-04-18 22:41 UTC, ernanirst commented on contracts/libraries/LibOriumNftMarketplace.sol
> +            'OriumNftMarketplace: only token owner can call this function'
On our implementation, `ownerOf` returns `address()` when the NFT is not deposited. However, if there was an implementation that returned the ERC-721 owner instead, this could become a vulnerability, right?

My question is, is it worth also adding a another call to make sure that the NFT is deposited in the contract **and** the ERC-7432 matches the sender?

2024-04-18 22:41 UTC, ernanirst commented on contracts/libraries/LibOriumNftMarketplace.sol
> +            'OriumNftMarketplace: tokenAddress is not trusted'
```suggestion
            'OriumNftMarketplace: tokenAddress or feeTokenAddress is not trusted'
```

2024-04-18 22:41 UTC, ernanirst commented on contracts/libraries/LibOriumNftMarketplace.sol
> +        require(msg.sender == _offer.lender, 'OriumNftMarketplace: Sender and Lender mismatch');
if the `msg.sender` must always be the lender, is that parameter necessary in the create rental offer function?

2024-04-18 22:41 UTC, ernanirst commented on contracts/OriumNftMarketplace.sol
> +        isCreated[_offerHash] = true;
I would rearrange these statements just so we immediately see why you are computing this hash
```suggestion
        bytes32 _offerHash = LibOriumNftMarketplace.hashRentalOffer(_offer);
        isCreated[_offerHash] = true;

        nonceDeadline[msg.sender][_offer.nonce] = _offer.deadline;
```

2024-04-19 12:45 UTC, karacurt commented on contracts/libraries/LibOriumNftMarketplace.sol
> +            'OriumNftMarketplace: only token owner can call this function'
Sure, we can do that

2024-04-19 21:22 UTC, ernanirst approved these changes

2024-04-19 21:22 UTC, ernanirst commented on contracts/NftRentalMarketplace.sol
> +        nonceDeadline[msg.sender][_offer.nonce] = _offer.deadline;
Should we move these storage operations for after the loop where we check the `roleDeadline`? Just to make sure we only touch the storage when the offer is fully validated

2024-04-22 14:53 UTC, merged