feat: Accept offer to pay with native token MARKETPLACE ERC-1155
OriumNetwork/orium-rental-marketplace-contracts pull request #59
Opened 2024-08-05 17:00 UTC by EduardoMelo00

feat: Accept offer to pay with native token MARKETPLACE ERC-1155

2024-08-12 13:52 UTC, ernanirst requested changes

2024-08-12 13:52 UTC, ernanirst commented on contracts/NftRentalMarketplace.sol
> +            uint256 lenderAmount = totalFeeAmount - marketplaceFeeAmount - royaltyAmount;
Isn't this the same logic inside the `LibNftRentalMarketplace.transferFees`?

Can't we extract this to a view or pure function and then transfer the tokens based on the `feeTokenAddress`? See how it's done in the ERC-1155 Marketplace

2024-08-12 13:52 UTC, ernanirst commented on contracts/OriumSftMarketplace.sol
> +            require(msg.value >= _feeAmount, 'OriumSftMarketplace: Insufficient native token amount');
Use the exact amount just in case.
```suggestion
            require(msg.value == _feeAmount, 'OriumSftMarketplace: Insufficient native token amount');
```

2024-08-12 14:53 UTC, EduardoMelo00 commented on contracts/OriumSftMarketplace.sol
> +            require(msg.value >= _feeAmount, 'OriumSftMarketplace: Insufficient native token amount');
I did the same to the nftMarketplace

2024-08-16 14:40 UTC, ernanirst approved these changes

2024-08-16 17:55 UTC, merged