feat: adding the splitter contract at marketplace contracts
OriumNetwork/orium-rental-marketplace-contracts pull request #61
Opened 2024-09-16 17:45 UTC by EduardoMelo00

2024-09-16 18:46 UTC, ernanirst requested changes

2024-09-16 18:46 UTC, ernanirst commented on contracts/SplitterContract.sol
> +    uint256 public constant MAX_SHARES = 10000;
```suggestion
    uint16 public constant MAX_SHARES = 10000;
```

2024-09-16 18:46 UTC, ernanirst commented on contracts/SplitterContract.sol
> +        uint256[][] calldata shares,
Since the maximum share is 10,000, make all share fields `uin16`
```suggestion
        uint16[][] calldata shares,
```

2024-09-16 18:46 UTC, ernanirst commented on contracts/SplitterContract.sol
> +    mapping(address => mapping(address => bool)) private _hasToken;
```suggestion
    // tokenAddress => userAddress => balance
    mapping(address => mapping(address => uint256)) public balances;
    // userAddress => tokenAddress[]
    mapping(address => address[]) private userTokens;
    // tokenAddress => boolean
    mapping(address => mapping(address => bool)) private hasToken;
```

2024-09-16 18:46 UTC, ernanirst commented on contracts/SplitterContract.sol
> +pragma solidity ^0.8.0;
Use the same license and solidity version we use on other contracts

2024-09-16 18:46 UTC, ernanirst commented on contracts/SplitterContract.sol
> +        require(userTokens.length > 0, 'ERC20Splitter: No tokens to withdraw');
Don't revert, simply return

2024-09-16 18:46 UTC, ernanirst commented on contracts/SplitterContract.sol
> +        uint256[] memory withdrawnAmounts = new uint256[](userTokens.length);
Instead of allocating memory and keep pushing items to the arrays, emit event before the loop

2024-09-16 18:46 UTC, ernanirst commented on contracts/SplitterContract.sol
> +                    (bool success, ) = msg.sender.call{ value: amount }('');
Do the following to avoid calling additional functions from the msg.sender
```
address payable to = payable(msg.sender);
to.transfer(getBalance());
```

2024-09-16 18:46 UTC, ernanirst commented on test/SplitterContract.test.ts
> +    describe('Deposit', async () => {
Add test for when the user send an incorrect msg.value

2024-09-16 18:46 UTC, ernanirst commented on contracts/SplitterContract.sol
> +contract ERC20Splitter is ReentrancyGuard {
Rename file to ERC20Splitter too

2024-09-16 18:46 UTC, ernanirst commented on test/SplitterContract.test.ts
> +  describe('Main Functions', async () => {
Bring branch test coverage to 100%

2024-09-17 17:35 UTC, ernanirst requested changes

2024-09-17 17:35 UTC, ernanirst commented on contracts/ERC20Splitter.sol
> +        emit Withdraw(to, withdrawnAmounts);
```suggestion
        emit Withdraw(to, userTokens[msg.sender], withdrawnAmounts);
```

2024-09-17 17:35 UTC, ernanirst commented on contracts/ERC20Splitter.sol
> +        address[] storage senderTokens = userTokens[to];
```suggestion
        address[] storage senderTokens = userTokens[msg.sender];
```

2024-09-17 17:35 UTC, ernanirst commented on contracts/ERC20Splitter.sol
> +                (bool success, ) = to.call{ value: amount }('');
user `transfer`
```suggestion
                (bool success, ) = payable(msg.sender).transfer(amount);
```

2024-09-17 21:06 UTC, ernanirst requested changes

2024-09-17 21:06 UTC, ernanirst commented on contracts/ERC20Splitter.sol
> +    event Withdraw(address indexed user, address[] tokenAddresses, uint256[] amounts);
A new requirement popped up, we need to emit events for each recipient on the loop (and index recipient, so they are searchable)

Let's sync on this

2024-09-17 21:06 UTC, ernanirst commented on contracts/ERC20Splitter.sol
> +        address payable to = payable(msg.sender);
```suggestion
```

2024-09-18 23:43 UTC, ernanirst requested changes

2024-09-18 23:43 UTC, ernanirst commented on contracts/ERC20Splitter.sol
> +            balances[tokenAddress][recipient] = 0;
This refunds gas, might help.
```suggestion
            delete balances[tokenAddress][recipient];
```

2024-09-18 23:43 UTC, ernanirst commented on contracts/ERC20Splitter.sol
> +        address recipient = msg.sender;
No need to copy `msg.sender` to memory. Also, calling it recipient and sender caused confusion

2024-09-18 23:44 UTC, ernanirst requested changes

2024-09-18 23:44 UTC, ernanirst commented on test/SplitterContract.test.ts
> +      it.only('Should deposit four ERC20 tokens and split them between recipients', async () => {
Test leftover
```suggestion
      it('Should deposit four ERC20 tokens and split them between recipients', async () => {
```

2024-09-20 13:54 UTC, ernanirst requested changes

2024-09-20 13:54 UTC, ernanirst commented on contracts/ERC20Splitter.sol
> +    /// Tokens are automatically determined based on previous deposits.
```suggestion
    /// @notice Withdraw all tokens that the caller is entitled to.
    /// Tokens are automatically determined based on previous deposits.
    /// @param tokenAddresses Array of token addresses (use address(0) for native tokens).
```

2024-09-20 13:54 UTC, ernanirst commented on contracts/ERC20Splitter.sol
> +        require(amount > 0, 'ERC20Splitter: Amount must be greater than zero');
Just noticed this. Don't revert when `amount` is zero, simply return

2024-09-20 13:54 UTC, ernanirst commented on contracts/ERC20Splitter.sol
> +            }
If you jump the loop here, the event will emit the array `withdrawnAmounts` with a different size than `tokenAddresses`. It can be confusing

2024-09-20 13:54 UTC, ernanirst commented on hardhat.config.ts
> +        timeout: 9999900,
This was an alchemy problem. Let's revert back to the original value

2024-09-20 13:54 UTC, ernanirst commented on test/SplitterContract.test.ts
> +describe('ERC20Splitter', () => {
Coverage is at 93%, is it because of `nonReentrant`? Or is there something else?

2024-09-20 14:12 UTC, EduardoMelo00 commented on test/SplitterContract.test.ts
> +describe('ERC20Splitter', () => {
Just because the reentrant
```
   function deposit(
        address[] calldata tokenAddresses,
        uint256[] calldata amounts,
        uint16[][] calldata shares,
        address[][] calldata recipients
    ) external payable EnonReentrant {
```

`function withdraw(address[] calldata tokenAddresses) external EnonReentrant {
`

2024-09-20 15:05 UTC, ernanirst approved these changes

2024-09-20 18:07 UTC, merged